import type { ConfigView, GraphData, ModelInfo, ReplayEntry, SessionInfo } from "./types";

const KEY = "openplanter:web:v2";
type DocumentRecord = { name: string; content: string; createdAt: string };
type WebStore = { config: ConfigView; sessions: SessionInfo[]; history: Record<string, ReplayEntry[]>; credentials: Record<string, string>; documents: DocumentRecord[] };
const defaults = (): WebStore => ({ config: { provider: "openrouter", model: "anthropic/claude-sonnet-4-5", reasoning_effort: null, workspace: "Browser workspace", session_id: null, recursive: true, max_depth: 4, max_steps_per_call: 100, demo: false }, sessions: [], history: {}, credentials: {}, documents: [] });
function read(): WebStore { try { const raw = localStorage.getItem(KEY); if (raw) return { ...defaults(), ...JSON.parse(raw) }; const old = localStorage.getItem("openplanter:web:v1"); return old ? { ...defaults(), ...JSON.parse(old), credentials: {} } : defaults(); } catch { return defaults(); } }
function save(s: WebStore) { localStorage.setItem(KEY, JSON.stringify(s)); }
export const isTauri = () => typeof window !== "undefined" && Boolean((window as Window & { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__);
export function webConfig(): ConfigView { return read().config; }
export function webUpdateConfig(partial: Partial<ConfigView>): ConfigView { const s = read(); s.config = { ...s.config, ...partial }; save(s); return s.config; }
export function webCredentials(): Record<string, boolean> { return Object.fromEntries(Object.entries(read().credentials).map(([k, v]) => [k, Boolean(v)])); }
export function webSaveCredential(provider: string, value: string) { const s = read(); if (value.trim()) s.credentials[provider] = value.trim(); else delete s.credentials[provider]; save(s); }
export function webSessions(): SessionInfo[] { return read().sessions; }
export function webOpenSession(id?: string): SessionInfo { const s = read(); const session = (id && s.sessions.find((x) => x.id === id)) || { id: crypto.randomUUID(), created_at: new Date().toISOString(), turn_count: 0, last_objective: null }; if (!s.sessions.some((x) => x.id === session.id)) s.sessions.unshift(session); s.config.session_id = session.id; save(s); return session; }
export function webDeleteSession(id: string) { const s = read(); s.sessions = s.sessions.filter((x) => x.id !== id); delete s.history[id]; save(s); }
export function webHistory(id: string) { return read().history[id] || []; }
export function webAddHistory(id: string, entry: ReplayEntry) { const s = read(); s.history[id] = [...(s.history[id] || []), entry].slice(-500); save(s); }
export function webModels(provider: string): ModelInfo[] { const models: Record<string, string[]> = { openrouter: ["anthropic/claude-sonnet-4-5", "openai/gpt-5", "moonshotai/kimi-k2", "z-ai/glm-4.5-air", "deepseek/deepseek-r1"], openai: ["gpt-5", "gpt-4.1-mini"], anthropic: ["claude-sonnet-4-5", "claude-haiku-4-5"], google: ["gemini-2.5-pro", "gemini-2.5-flash"], ollama: ["llama3.2", "qwen3:8b"], lmstudio: ["local-model"] }; return (models[provider] || models.openrouter).map((id) => ({ id, name: id, provider })); }
export function webGraph(): GraphData { const docs = read().documents; return { nodes: docs.map((d, i) => ({ id: `doc-${i}`, label: d.name, category: "document", path: d.name, node_type: "source" as const })), edges: [] }; }
export function webSaveDocument(name: string, content: string) { const s = read(); s.documents = [...s.documents.filter((d) => d.name !== name), { name, content, createdAt: new Date().toISOString() }]; save(s); }
export function webDocuments() { return read().documents; }
export function downloadText(filename: string, content: string, type = "text/markdown") { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = filename; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function exportWorkspace() { downloadText("openplanter-backup.json", JSON.stringify(read(), null, 2), "application/json"); }
export async function importWorkspace(file: File) { const incoming = JSON.parse(await file.text()) as WebStore; if (!incoming || !incoming.config || !Array.isArray(incoming.sessions)) throw new Error("Invalid OpenPlanter backup"); save({ ...defaults(), ...incoming }); location.reload(); }
export function wipeWorkspace() { localStorage.removeItem(KEY); localStorage.removeItem("openplanter:web:v1"); localStorage.removeItem("openplanter:evidence"); localStorage.removeItem("openplanter:favorites"); localStorage.removeItem("openplanter:profile"); localStorage.removeItem("openplanter:spend-limit"); location.reload(); }
export async function importFolder(files: FileList | File[]) { for (const file of Array.from(files)) { if (file.size <= 2_000_000) webSaveDocument(file.webkitRelativePath || file.name, await file.text()); } }
export function exportFindings() { const s = read(); const notes = JSON.parse(localStorage.getItem("openplanter:evidence") || "[]"); const body = `# OpenPlanter Findings\n\n## Documents\n${s.documents.map((d) => `### ${d.name}\n\n${d.content}`).join("\n\n")}\n\n## Evidence\n${notes.map((n: { text: string; contradiction: boolean }) => `- ${n.contradiction ? "[CONTRADICTION] " : ""}${n.text}`).join("\n")}`; downloadText("openplanter-findings.md", body); }
const endpoints: Record<string, string> = { openrouter: "https://openrouter.ai/api/v1", openai: "https://api.openai.com/v1", google: "https://generativelanguage.googleapis.com/v1beta/openai", ollama: "http://localhost:11434/v1", lmstudio: "http://localhost:1234/v1" };
export async function webSolve(objective: string, sessionId: string, signal?: AbortSignal) { const s = read(); const key = s.credentials[s.config.provider]; if (!key) throw new Error(`Add a ${s.config.provider} API key in Settings first.`); const started = Date.now(); const inputTokens = Math.max(1, Math.ceil(objective.length / 4)); window.dispatchEvent(new CustomEvent("agent-step", { detail: { depth: 0, step: 1, tool_name: null, tokens: { input_tokens: inputTokens, output_tokens: 0 }, elapsed_ms: 0, is_final: false } })); const messages = (s.history[sessionId] || []).filter((x) => x.role === "user" || x.role === "assistant").slice(-20).map((x) => ({ role: x.role, content: x.content })); messages.push({ role: "user", content: objective }); const response = await fetch(`${endpoints[s.config.provider] || endpoints.openrouter}/chat/completions`, { method: "POST", signal, headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}`, ...(s.config.provider === "openrouter" ? { "HTTP-Referer": location.origin, "X-Title": "OpenPlanter" } : {}) }, body: JSON.stringify({ model: s.config.model, messages, stream: true, temperature: 0.2 }) }); if (!response.ok) throw new Error(`${response.status}: ${(await response.text()).slice(0, 300)}`); if (!response.body) throw new Error("Provider returned no response stream."); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let result = ""; const emit = (text: string) => { result += text; window.dispatchEvent(new CustomEvent("agent-chunk", { detail: { text, result } })); }; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split("\n"); buffer = lines.pop() || ""; for (const line of lines) { if (!line.startsWith("data:")) continue; const data = line.slice(5).trim(); if (data === "[DONE]") continue; try { const delta = JSON.parse(data).choices?.[0]?.delta?.content; if (delta) emit(delta); } catch { /* ignore incomplete SSE frames */ } } } if (!result.trim()) throw new Error("The model returned an empty response."); webAddHistory(sessionId, { seq: webHistory(sessionId).length, timestamp: new Date().toISOString(), role: "assistant", content: result, is_rendered: true }); window.dispatchEvent(new CustomEvent("agent-step", { detail: { depth: 0, step: 1, tool_name: null, tokens: { input_tokens: inputTokens, output_tokens: Math.max(1, Math.ceil(result.length / 4)) }, elapsed_ms: Date.now() - started, is_final: true } })); window.dispatchEvent(new CustomEvent("agent:complete", { detail: { result } })); }
export function webCancel() { /* fetch is aborted by invoke layer */ }
export function webAbortController() { return new AbortController(); }
export function clearWebData() { wipeWorkspace(); }
export function getWebBackup() { return read(); }
export function restoreWebBackup(data: WebStore) { save({ ...defaults(), ...data }); }
export type { WebStore };
